# Note: This is adapted from LukeMathWalker/zero-to-production/.github/workflows/audit.yml

name: Security audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main, dev]
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
